export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_CHANGE_SUCCESS = 'AUTH_CHANGE_SUCCESS';
export const AUTH_DP_SUCCESS = 'AUTH_DP_SUCCESS';
export const AUTH_INIT_ERROR = 'AUTH_INIT_ERROR';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_PROFILE_FEED = 'FETCH_PROFILE_FEED';
export const FETCH_FAILED = 'FETCH_FAILED';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';

export const INIT_DATALIST = 'INIT_DATALIST';
